apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: yippy-cluster
  region: us-east-1
  version: "1.19"
nodeGroups:
  - name: broken-ng-1
    amiFamily: "Bottlerocket"
    instanceType: "t3.medium"
    ssh:
        publicKeyName: nitish-ec2-useast-1
        allow: true
    