apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test2
  region: us-east-1
  version: "1.18"

nodeGroups:
   - name: seplication
     amiFamily: "Ubuntu2004"
     instanceType: "t3.medium"
     ssh:
        publicKeyName: nitish-ec2-useast-1
        allow: true
