apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: vault
  region: us-east-1
  version: "1.20"

nodeGroups:
   - name: eplication
     minSize: 1
     maxSize: 3
     desiredCapacity: 1
     ssh:
        publicKeyName: nitish-ec2-useast-1
        allow: true
