kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: replicationd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zones: us-east-1d, us-east-1b
  iopsPerGB: "10" 
  fsType: ext4
