apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: replication-cluster
  region: us-east-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  subnets:
    private:
      us-east-1f:
        id: subnet-xxx
      us-east-1c:
        id: sunetxxx



managedNodeGroups:
- name: m1
  instanceType: m5.large
  desiredCapacity: 2
  privateNetworking: true
