apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rep-private-cluster
  region: us-east-1
  version: "1.21"

privateCluster:
  enabled: true

vpc:
  subnets:
    private:
      us-east-1f:
        id: 
      us-east-1c:
        id: 

managedNodeGroups:
- name: m2
  instanceType: m5.large
  desiredCapacity: 2
  privateNetworking: true
  amiFamily: Bottlerocket
  iam:
     attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

