apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 893524292628.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
          ports:
            - name: http
              containerPort: 80
