apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slow
  labels:
    app: nginx
spec:
  storageClassName: replicationd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

